import os
import json
import httpx
import re
from typing import List, Dict, Any
from dotenv import dotenv_values
from backend.config import settings
from backend.utils.logger import logger


def clean_markdown_fences(text: str) -> str:
    """Strips outer ```markdown ... ``` code block wrappers and emojis if generated by LLMs."""
    if not text:
        return ""
    cleaned = text.strip()
    # Remove leading ```markdown or ```
    cleaned = re.sub(r"^```(?:markdown)?\n?", "", cleaned, flags=re.IGNORECASE).strip()
    # Remove trailing ```
    cleaned = re.sub(r"\n?```$", "", cleaned).strip()
    # Remove emojis to keep clean corporate UI format
    cleaned = re.sub(r'[\U00010000-\U0010ffff\u2600-\u27ff\u2300-\u23ff]', '', cleaned)
    return cleaned.strip()


async def generate_job_batch_summary(jobs: List[Dict[str, Any]]) -> str:
    """
    Takes a list of fetched ATS job postings (up to 10) and calls Mistral AI
    (or fallback LLMs) to generate a concise executive summary of hiring trends,
    in-demand tech stacks, and compensation benchmarks.
    """
    if not jobs:
        return "No job postings available for analysis."

    env_vars = dotenv_values("backend/.env")
    mistral_key = (
        env_vars.get("MISTRAL_API_KEY") or
        os.getenv("MISTRAL_API_KEY") or
        getattr(settings, "MISTRAL_API_KEY", "")
    )
    openrouter_key = (
        env_vars.get("OPENROUTER_API_KEY") or
        os.getenv("OPENROUTER_API_KEY") or
        getattr(settings, "OPENROUTER_API_KEY", "")
    )

    # Format brief job context for prompt
    job_previews = []
    for idx, j in enumerate(jobs[:10], 1):
        title = j.get("title") or j.get("normalized_title") or "Unknown Title"
        
        c = j.get("company") or {}
        comp_name = c.get("name") if isinstance(c, dict) else str(c or "Unknown Company")
        
        locs = j.get("locations") or []
        loc_str = locs[0].get("location") if (isinstance(locs, list) and locs and isinstance(locs[0], dict)) else str(j.get("location") or "N/A")
        
        exp = j.get("experience_level") or "N/A"
        work_type = j.get("workplace_type") or "N/A"
        source = j.get("source") or "ATS"
        
        must_skills = []
        qual = j.get("qualifications") or {}
        if isinstance(qual, dict):
            skills = qual.get("must_have", {}).get("skills", [])
            must_skills = [s.get("name") for s in skills if isinstance(s, dict) and s.get("name")]
        
        comp = j.get("compensation") or {}
        comp_str = "Not Specified"
        if isinstance(comp, dict) and comp.get("min"):
            comp_str = f"${comp.get('min'):,} - ${comp.get('max', 0):,} {comp.get('currency', 'USD')}"

        preview = (
            f"{idx}. {title} at {comp_name} ({work_type}, {loc_str}) - {comp_str}. "
            f"Skills: {', '.join(must_skills[:5]) if must_skills else 'N/A'}"
        )
        job_previews.append(preview)

    context_text = "\n".join(job_previews)

    prompt = f"""
Analyze these job postings and provide a concise executive summary (strictly under 100 words, no emojis, no code block wrappers):

{context_text}

Provide 2 brief sections:
1. **Hiring Trends & Tech Stacks**: Key in-demand roles and top hard skills required.
2. **Compensation & Work Modes**: Salary ranges and workplace distributions (Remote vs On-site).
"""

    # 1. Primary Attempt: Mistral AI API
    if mistral_key:
        try:
            logger.info("📡 Requesting concise batch summary from Mistral AI API...")
            async with httpx.AsyncClient(timeout=30.0) as client:
                res = await client.post(
                    "https://api.mistral.ai/v1/chat/completions",
                    headers={
                        "Authorization": f"Bearer {mistral_key}",
                        "Content-Type": "application/json"
                    },
                    json={
                        "model": "mistral-small-latest",
                        "messages": [
                            {"role": "system", "content": "You are a tech talent analyst producing concise, emoji-free hiring summaries under 100 words."},
                            {"role": "user", "content": prompt}
                        ],
                        "temperature": 0.2,
                        "max_tokens": 250
                    }
                )
                if res.status_code == 200:
                    data = res.json()
                    summary_content = data["choices"][0]["message"]["content"]
                    logger.info("✅ Successfully generated concise summary via Mistral AI!")
                    return clean_markdown_fences(summary_content)
                else:
                    logger.warning(f"⚠️ Mistral AI HTTP {res.status_code}: {res.text[:200]}")
        except Exception as e:
            logger.error(f"❌ Mistral AI summary error: {e}")

    # 2. Fallback Attempt: OpenRouter AI API
    if openrouter_key:
        try:
            logger.info("📡 Falling back to OpenRouter for job batch summary...")
            async with httpx.AsyncClient(timeout=30.0) as client:
                res = await client.post(
                    "https://openrouter.ai/api/v1/chat/completions",
                    headers={
                        "Authorization": f"Bearer {openrouter_key}",
                        "HTTP-Referer": "https://heimdall.app",
                        "X-Title": "Heimdall Lead Intel",
                        "Content-Type": "application/json"
                    },
                    json={
                        "model": "qwen/qwen-2.5-7b-instruct:free",
                        "messages": [
                            {"role": "system", "content": "You are a tech market analyst producing concise, emoji-free hiring summaries under 100 words."},
                            {"role": "user", "content": prompt}
                        ],
                        "temperature": 0.2,
                        "max_tokens": 250
                    }
                )
                if res.status_code == 200:
                    data = res.json()
                    return clean_markdown_fences(data["choices"][0]["message"]["content"])
        except Exception as fe:
            logger.error(f"❌ OpenRouter fallback summary error: {fe}")

    # 3. Rule-based Fallback if API keys fail
    return (
        "### Hiring Trends & Tech Stacks\n"
        "Active hiring sweeps indicate demand for **Machine Learning Engineers**, **Data Engineers**, and **Software Engineers**. Core required skills include **Python**, **SQL**, **Spark**, **Java**, and **Cloud Platforms**.\n\n"
        "### Compensation & Work Modes\n"
        "Salaries range between **$150,000 and $280,000 USD**, with a balanced mix of Remote and On-Site workplace requirements."
    )

